channable/icepeak

- app/Icepeak.hs
- icepeak.cabal
- src/Core.hs
- src/Logger.hs
- src/WebsocketServer.hs
Using putStrLn in a number of concurrent threads leads to garbled output.
We therefore use a TBQueue for log messages as well and have a separate
logging loop that writes them to stdout one after the other leading to
nice logs.
> Add a logging system

- .gitignore
- README.md
- app/Icepeak.hs
- icepeak.cabal
- integration-tests/persistence_test.py
- package.yaml
- src/Config.hs
- src/Core.hs
This PR adds a basic persistence mechanism:
- After every operation is applied to the internal data representation the data is also written to disk
- Data is simply written to a file as plain-text Json
- The user can specify the location of the file
- On startup icepeak will read back the data from disk
We don't focus on performance here or worry about the (small) data loss possibility due to the HTTP loop and the operations loop not being synchronized. The goal is simply to get icepeak into a usable state.
> Persist the Json data

- server/integration-tests/listener.html
- server/src/Subscription.hs
- server/src/WebsocketServer.hs
- server/tests/SubscriptionTreeSpec.hs
Fixes #5.
Also adds more functionality to `listener.html`, that is useful for debugging.
Also adds a pure variant of `broadcast`, which returns a list of notifications instead of sending the notifications.
> Notify subscribers of changes to child nodes

- server/integration-tests/stress_test.hs
- server/src/Core.hs
We don't need to convert to lazy text first, to then convert back to UTF-8,
when Aeson already supports serialization to UTF-8 directly.
> Serialize JSON more efficiently

- docs/data-management.md
- server/.gitignore
- server/app/Icepeak/Main.hs
- server/integration-tests/data-survives-crash.sh
- server/package.yaml
- server/src/Config.hs
- server/src/Core.hs
- server/src/HttpServer.hs
- server/src/Logger.hs
- server/src/Metrics.hs
- server/src/Persistence.hs
- server/src/Store.hs
- server/src/Types.hs
- server/src/WebsocketServer.hs
- server/tests/CoreSpec.hs
- server/tests/OrphanInstances.hs
- server/tests/PersistenceSpec.hs
- server/tests/Spec.hs
- server/tests/StoreSpec.hs
If enabled (only applicable in combination with periodic syncing), every modification is written to a journal before being applied to the internal JSON value. When writing the latest version to disk, the journal is cleared.
If the journal is not empty when starting up, Icepeak recovers the database by replaying all modifications in the journal to the stored value. This allows to recover most or all of the data even in the case of a hard crash (i.e. power outage).
This addresses the second part of #19.
> Implement journaling

- server/app/Icepeak/Main.hs
- server/src/MetricsServer.hs
- server/src/Server.hs
Every log message is now going through the `Logger` module, fixing that messages
were sometimes printed somewhat interleaved. Moreover `stdout` is set to line
buffering to make sure every log entry is written as soon as it is ready.
> Fix logging

- server/app/Icepeak/Main.hs
- server/integration-tests/using-different-ports.sh
- server/src/Config.hs
- server/src/Server.hs
Fixes #12. Port is configurable through --port and $ICEPEAK_PORT.
Added a test for it:
```
icepeak/server$ integration-tests/using-different-ports.sh 
PASSED
PASSED
PASSED
PASSED
PASSED
PASSED
ALL PASSED
```
> Make icepeak port configurable

- server/src/Persistence.hs
If we cannot find a database at the configured file path we used to
crash with a not terribly good error message.
This PR instead logs a warning and then creates an empty database
(an empty JSON object: {}). Note, that the object will only be
persisted when some changes are written to disk.
> Create an empty database if there is none yet

- client-haskell/src/Icepeak/Client.hs
- server/integration-tests/auth_stress_test.hs
- server/integration-tests/stress_test.hs
In most use cases, you want to propagate these two together anyway. It is still
possible not to, if you want.
This is a breaking change, but we use commit-pinned versions so it's not an issue for us. People who use master as their reference will have to change their code.
> Pair HTTP manager with client details in one type

- client-haskell/stack.yaml
- server/app/IcepeakTokenGen/Main.hs
- server/integration-tests/generate_test_token.hs
- server/integration-tests/stress_test.hs
- server/src/Config.hs
- server/src/JwtAuth.hs
- server/src/JwtMiddleware.hs
- server/src/Logger.hs
- server/stack.yaml
- server/tests/JwtSpec.hs
There were some breaking changes in `haskell-jwt` which was upgraded from
v0.7.2 to v0.10.0.
Notably:
```haskell
newtype Secret = Secret BS.ByteString
```
changed to
```haskell
data Signer = HMACSecret BS.ByteString
| RSAPrivateKey PrivateKey
```
And
```haskell
type ClaimsMap = Map Text Value```
```
changed to
```haskell
newtype ClaimsMap = ClaimsMap { unClaimsMap :: Map.Map T.Text Value }
```
And
```haskell
encodeSigned :: Algorithm -> Secret -> JWTClaimsSet -> JSON
encodeUnsigned :: JWTClaimsSet -> JSON
```
changed to
```haskell
encodeSigned :: Signer -> JOSEHeader -> JWTClaimsSet -> Text
encodeUnsigned :: JWTClaimsSet -> JOSEHeader -> Text
```
Fortunately they documented all of this in their changelog, otherwise
I would have had to diff this with the help of `git log` /s
> Upgrade Stack from LTS 12.6 to LTS 14.0

- server/integration-tests/auth_stress_test.hs
- server/integration-tests/generate_test_token.hs
- server/integration-tests/stress_test.hs
For some reason the behavior of stack runghc changed and we have to pass icepeak{,-client} explicitly and not pass GHC options.
GHC options are now passed with OPTIONS_GHC.
> Make integration tests work with latest Stack

- client-haskell/src/Icepeak/Client.hs
Fixes an issue where the retry policy would not be respected, but an error was thrown and immediately the call site was notified of the failure, without attempting a retry.
> Fix the retry policy of Icepeak Client

- client-haskell/stack.yaml
- server/src/WebsocketServer.hs
- server/stack.yaml
There was one API change in the websockets library. The `forkPingThread`
function is now deprecated and has been replaced by the `withPingThread`
function. The latter one uses `withAsync` instead of `forkIO`, which the
former one used. This is only an internal change and has no externally
visible effects.
> Upgrade stack from LTS 14.0 to LTS 14.20

- nix/nixpkgs.nix
- nix/websockets.nix
- server/.gitignore
- server/default.nix
- server/package.yaml
- server/server.nix
Add a Nix package definition for Icepeak.
```
$ cd server
$ nix build
```
Nix is a purely functional build system. It can be used to build software and their dependencies. Read [The Nix Ecosystem](https://nixos.wiki/wiki/Nix_Ecosystem) for a high level introduction.
This PR uses Nix to build Icepeak. Nix and the extended Nix ecosystem enable us to define the exact dependencies that were used in order to build a package.
Internally, Channable is starting to use Nix for more things. This PR is part of our efforts to gain more experience in using Nix for all types of software. This PR might also help us easily build and distribute icepeak binaries.
Read https://nixos.org/nixos/nix-pills/ for an introduction to the Nix language and to derivations.
Nixpkgs contains a large collection of …
> Build/package with Nix

- client-haskell/client.nix
- client-haskell/package.yaml
It built before, but it was just an empty library. It wasn't detected because we didn't explicitly specify the modules in `package.yaml`, leaving it for hpack to discover which modules there are.
> nix: Actually include client module in derivation

- client-haskell/stack.yaml
- server/package.yaml
- server/stack.yaml
This also upgrades GHC from 8.6 to 8.8. There have been no breaking
changes and the tests are still passing. I did have to add sqlite-simple
and direct-sqlite as extra-deps, since they are no longer in the
stackage snapshot.
Why upgrade?
I have been on a [quixotic quest](https://github.com/NixOS/nixpkgs/pull/79155) to get Icepeak added to the Nixpkgs archive. And nixpkgs recently upgraded their supported GHC version from 8.6 to 8.8, and it's therefore necessary to upgrade here as well, because I can then release a new version of Icepeak on Hackage, which can then be downloaded by an automatic script `hackage2nix`, which will generate a Nix derivation for Icepeak, that is then added to Nixpkgs. :see_no_evil:
> Upgrade stack from LTS 14.23 to 15.3

- server/src/Metrics.hs
Pull request to fix #23. This PR:
- Expands the `IcepeakMetrics` data structure with two extra fields that follow the recommended Prometheus naming scheme.
- Changes the  `incrementDataWritten` and `setDataSize` to write to both the old and new metrics.
- Adds TODO comments indicating which lines can be removed later. The resulting lines are a bit long for my liking but that is all the more incentive to update the dashboard soon so that they can be removed :)
By adding the new metrics first, it'll become possible to update any dashboards (as mentioned in the linked issue) and then in a second PR the old metrics can be removed. I'm unsure what the best new name for the HTTP request counter metric would be. It could be something like `icepeak_http_requests_total`?
> Add metrics with recommended Prometheus naming scheme

- .travis.yml
I noticed when working on #65 that the travis CI system took quite long (16 minutes for my branch, between ~8 and ~30 minutes [in the build history on Travis](https://travis-ci.org/github/channable/icepeak/builds)). The Coronavirus also struck Almere, so I'm bored and decided to speed it up.
This PR:
- Splits the four tasks in the Travis CI file into their own job so that they can run in parallel. Travis allows parallel jobs even for open source projects.
- Optimizes the caching and setup for each of the resulting jobs. (Testing the server does not need the stack cache for the client and vice versa, for example)
- Changes the Travis base image from `c` to `minimal` ([link to docs](https://docs.travis-ci.com/user/languages/minimal-and-generic/)). This does not really matter too much for …
> Travis speed

- client-haskell/default.nix
- client-haskell/src/Icepeak/Client.hs
- client-haskell/stack.yaml
- nix/nixpkgs.nix
- server/package.yaml
- server/stack.yaml
This upgrades GHC from 8.8.2 to 8.8.4. This is necessary to stay compatible with the
master branch of nixpkgs. Icepeak was marked as broken there, since it
couldn't be built any more with the GHC and libraries available there.
Also update the Stack LTS release from 15.3 to 16.23.
This will then allows us to cut a 0.7.4 release, and get that included into nixpks to unbreak it.
> Update nixpkgs snapshot

- LICENSE
- README.md
- client-haskell/client.nix
- client-haskell/stack.yaml
- nix/nixpkgs.nix
- server/package.yaml
- server/server.nix
- server/stack.yaml
This requires bumping the nixpkgs revision. The latest nixpkgs-unstable revision contains GHC 8.10.3, which we are now using. There were no breaking changes in any of our dependencies.
> Upgrade stack from LTS 16.23 to 17.2 (GHC 8.8 -> 8.10)

- .semaphore/report-cronjob-failure.sh
- .semaphore/report-cronjob-start.sh
- .semaphore/report-cronjob-success.sh
- .semaphore/vulnix-nightly.yml
- server/shell.nix
- server/vulnix-ignorelist.toml
This PR is related to channable/devops/issues/3773
This PR adds a nightly run CI job that checks if there are no known CVE's in our dependencies, using Vulnix.
Vulnix is setup up to use a large ignorelist that makes sure that the CI does not start failing immediately.
There are issues created for the package updates we have to perform: #70 and #71, which are linked in the ignorelist to the right CVE's
I have tested the CI setup in a seperate branch. You can find the result here: https://channable.semaphoreci.com/workflows/d7ded8d6-be3e-4057-8054-1e05ab34a2b9?pipeline_id=333c929f-62b8-4d19-ae8b-9a0c22d52a6c
> Add Vulnix as a nightly CI job

- client-haskell/default.nix
- client-haskell/stack.yaml
- nix/nixpkgs.nix
- server/default.nix
- server/package.yaml
This required bumping nixpkgs. No code changes were required.
We now include stack in the nix environment, so that we don't have
to depend on stack being installed externally.
> Upgrade stack from LTS 17.2 to 18.18

- client-haskell/stack.yaml
- nix/sources.json
- server/app/IcepeakTokenGen/Main.hs
- server/package.yaml
- server/src/Config.hs
- server/src/JwtAuth.hs
- server/src/JwtMiddleware.hs
- server/src/Store.hs
- server/stack.yaml
- server/tests/JwtSpec.hs
- server/tests/OrphanInstances.hs
- server/tests/StoreSpec.hs
This PR upgrades the stackage snapshot from 18.18 to 19.17.
This implies a GHC upgrade from 8.10 to 9.0.
There were breaking changes in two libraries:
- `Web.JWT` has split the Signer datatype into two versions: EncodeSigner and VerifySigner. The former is used to encode
newly minted tokens, while the latter is used to verify signed tokens.
- `Data.Aeson` has hidden the `HashMap` type behind a `KeyMap` type which only exposes `alterF` instead of `alter` and `adjust`. I added the last two functions to keep the rest of the code the same.
All the tests are passing again.
> Upgrade from LTS 18.18 to 19.17 and fix all breaking changes

- server/src/Config.hs
- server/src/Core.hs
- server/src/Persistence.hs
Before releasing, so not to break past behaviour, I preferred to add toggling for the Sync operation log.
> Enable log toggling for Sync operations.

- server/default.nix
- server/icepeak-server.nix
- server/integration-tests/multiple_clients_test.py
Related to issue https://github.com/channable/icepeak/issues/87. 
I added the python dependencies needed for the integration tests, but didn't add GMP to the list since Icepeak builds successfully using `stack build --nix`.
> Add python dependencies in Nix configuration files for the server.

- server/src/Persistence.hs
Fixes https://github.com/channable/icepeak/issues/94: I added support for logging of the duration of logging operations, including average, minimum and maximum, over the time frame between two Sync operations.
> Add logging on duration of journaling operations

- server/src/Core.hs
We want to avoid dependency of one thread to a blocking queue, by stopping writing in it if it's full, thus discarding the update. This is not the best model and needs to be improved on, but it can serve as a fix in some cases.
> Basic fix for avoiding blocking of the consumer thread.

- server/src/Core.hs
- server/src/Metrics.hs
- server/src/WebsocketServer.hs
We wanted to observe how this queue grows and shrinks over time. The metrics are available on the Prometheus endpoint.
> Add metrics on WebSocket queue

- server/src/Config.hs
- server/src/Core.hs
- server/src/Subscription.hs
- server/src/WebsocketServer.hs
- server/tests/JwtSpec.hs
- server/tests/OrphanInstances.hs
The previous model for subscribers was monolithic: one thread was managing all the subscribers, and if one of them failed to answer, it could block the entire subscribers mechanism. We want to avoid this "single point of failure" kind of architecture, so we opted for a different thread model.
Now, for *each* subscriber, we have a dedicated thread that handles sending the updates to them. This thread is killed on timeout or unsubscribing. Icepeak's main thread feeds these threads through dedicated bounded queues (one per subscriber).
This PR starts as a draft because I want https://github.com/channable/icepeak/pull/100 merged first.
> Change threading model for subscribers

- server/src/Core.hs
- server/src/Metrics.hs
- server/src/WebsocketServer.hs
Fixes https://github.com/channable/icepeak/issues/103.
I reused the already existing metric, because the user-facing issue would be the same, and we can easily know in which case we are looking at the size of the queue (which can be computed from other metrics).
> Increase WebSocket skipped updates metric when queue is not fetched

- docs/IcepeakProtocolMultiSub.md
- server/icepeak.cabal
- server/icepeak.nix
- server/src/Icepeak/Server/Config.hs
- server/src/Icepeak/Server/Core.hs
- server/src/Icepeak/Server/WebsocketServer.hs
- server/src/Icepeak/Server/WebsocketServer/MultiSubscription.hs
- server/src/Icepeak/Server/WebsocketServer/Payload.hs
- server/src/Icepeak/Server/WebsocketServer/SingleSubscription.hs
- server/src/Icepeak/Server/WebsocketServer/Utils.hs
- server/tests/Icepeak/Server/MultiSubscriptionSpec.hs
- server/tests/Spec.hs
Added 2 additional modules to separate new behaviour from old:
```
Icepeak.Server.WebsocketServer.HandleClientSingleSubscription
Icepeak.Server.WebsocketServer.HandleClientMultiSubscription
```
Current draft implements the ability for the client thread to :
- Client thread to case split on payloads, and sub and un-sub from the subscription tree accordingly.
- Client thread to receive and read from multiple paths in the subscription tree, and send to socket.
- Client thread to disconnect, and clean up the subscription tree after itself.
Left to do:
> Multi Subscription Single Connection
